FHIQC-23 Upgrade to VertX 4.3.4
folio-org/folio-holdingsiq-client pull request #66
Opened 2022-10-04 12:38 UTC by Shans-Kaluhin

## Approach
- Update dependencies
- Update NEWS

### Learning
https://issues.folio.org/browse/FHIQC-23

2022-10-04 14:13 UTC, viacheslavkol approved these changes

2022-10-05 08:36 UTC, psmagin requested changes

2022-10-05 08:36 UTC, psmagin commented on pom.xml
> +    <jackson.version>2.14.0-rc1</jackson.version>
release candidates should not be part of the dependencies

2022-10-05 12:26 UTC, psmagin approved these changes

2022-10-05 13:37 UTC, merged