FHIQC-30: Update the module for Java 17 & the latest dependencies
folio-org/folio-holdingsiq-client pull request #72
Opened 2023-03-21 22:59 UTC by shorasul96

## Purpose
_Preparing module for next version of java 17 and updating dependecies_

## Approach
_Updated maven-compiler-plugin version to 17_
_Updated log4j version to 2.20.0_
_Updated vertx version to 4.4.0_

2023-03-22 10:30 UTC, psmagin requested changes

2023-03-22 10:30 UTC, psmagin commented on NEWS.md
> +## 2.4.0 2023-03-22
Migrating to Java 17 is a breaking change so update module version to 3.0.0

and these was not released yet so replace date with in progress

2023-03-24 17:26 UTC, psmagin requested changes

2023-03-24 17:26 UTC, psmagin commented on pom.xml
>      <folio-service-tools.version>1.10.1</folio-service-tools.version>
Have to be changed to 3.x.x-snapshot

2023-03-27 09:55 UTC, viacheslavkol requested changes

2023-03-27 09:55 UTC, viacheslavkol commented on NEWS.md
> +* Bump `folio-service-tools` from `1.10.0` to `3.1.0-SNAPSHOT`
You should not change news for released version.
Version bump from 1.10.1 to 3.1.0 should be in 3.0.0 version section

2023-03-27 14:52 UTC, psmagin approved these changes

2023-03-27 16:52 UTC, ArtHov approved these changes

2023-03-28 11:32 UTC, merged