FHIQC-31: Update GET /eholdings/resources/resourceId to include proxiedUrl
folio-org/folio-holdingsiq-client pull request #76
Opened 2023-04-18 11:39 UTC by shorasul96

## Purpose
_Add this new field [proxiedUrl] TO GET /eholdings/resources/ {resourceId}_
_By adding this new field then the field will display on the View package-title (aka resource) record_

## Approach
_Added a new field into Proxy class_

2023-04-19 06:03 UTC, hasanepam approved these changes

2023-04-19 15:43 UTC, psmagin requested changes

2023-04-19 15:43 UTC, psmagin commented on src/main/java/org/folio/holdingsiq/model/Proxy.java
`Proxy` class is using not only by `CustomerResources`( the class that is used in response to /eholdings/resources/resourceId endpoint) but and by other classes and endpoints, the response of which is not changed.
So, to not brake all other endpoints I suggest to have a separate class that will have all that Proxy have and proxiedUrl. And then use this new class in proper case that will extend the endpoint response.

2023-04-21 07:28 UTC, psmagin approved these changes

2023-04-21 08:10 UTC, merged